# Generated by Django 4.1.7 on 2023-04-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_atendimento_quantidade_alter_atendimento_valor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atendimento',
            new_name='PostoAtendimento',
        ),
    ]
