# Generated by Django 4.1.7 on 2023-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_valor_postoatendimento_valorpago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoatendimento',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='postoatendimento',
            name='valorPago',
            field=models.FloatField(),
        ),
    ]
