# Generated by Django 4.1.7 on 2023-04-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_postoatendimento_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoatendimento',
            name='novoCliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
