# Generated by Django 4.1.7 on 2023-04-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_cliente_cpf_postoatendimento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postoatendimento',
            name='nome',
        ),
        migrations.AddField(
            model_name='postoatendimento',
            name='nome',
            field=models.ManyToManyField(to='app.cliente', verbose_name='Funcionários'),
        ),
    ]
