# Generated by Django 4.1.7 on 2023-04-01 22:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_postoatendimento_nome_postoatendimento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postoatendimento',
            name='nome',
        ),
        migrations.AddField(
            model_name='postoatendimento',
            name='nome',
            field=models.CharField(default=0, max_length=100, verbose_name=app.models.Cliente),
            preserve_default=False,
        ),
    ]
