# Generated by Django 4.1.7 on 2023-04-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_atendimento_postoatendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postoatendimento',
            old_name='valor',
            new_name='valorPago',
        ),
        migrations.RemoveField(
            model_name='postoatendimento',
            name='tipoVeiculo',
        ),
    ]
