# Generated by Django 4.1.7 on 2023-04-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_postoatendimento_novocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postoatendimento',
            name='novoCliente',
        ),
    ]
