# Generated by Django 4.1.7 on 2023-04-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_postoatendimento_novocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.AddField(
            model_name='postoatendimento',
            name='nome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
