# Generated by Django 4.1.7 on 2023-04-01 22:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_postoatendimento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postoatendimento',
            name='cpf',
            field=models.CharField(default=0, max_length=50, verbose_name=app.models.Cliente),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postoatendimento',
            name='nome',
            field=models.CharField(max_length=50, verbose_name=app.models.Cliente),
        ),
    ]
