# Generated by Django 4.1.7 on 2023-04-01 22:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cliente_cpf_postoatendimento_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='postoatendimento',
            name='cpf',
            field=models.IntegerField(max_length=50, verbose_name=app.models.Cliente),
        ),
    ]
