# Generated by Django 4.1.7 on 2023-04-02 01:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cliente_cpf_alter_postoatendimento_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postoatendimento',
            name='cpf',
            field=models.IntegerField(verbose_name=app.models.Cliente),
        ),
        migrations.AlterField(
            model_name='postoatendimento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name=app.models.Cliente),
        ),
    ]
